### ISSUE TITLE
I'm getting below error when i migrate the Inherited process by using the Process-migrator tool, so please suggest work arounds for this

### ISSUE THREAD

**Issue by rakeshkasoju** [Microsoft/process-migrator#11]
Begin step 'Create picklist for field CMMI_D365.BugSourceLevel'.
[VERBOSE] [2018-06-15T07:34:01.547Z] Finished step 'Create picklist for field CMMI_D365.BugSourceLevel'.
[VERBOSE] [2018-06-15T07:34:01.547Z] Begin step 'Create picklist for field CMMI_D365.Scope'.
[VERBOSE] [2018-06-15T07:34:01.644Z] Exception message:You must provide a value for the Items parameter.
Call stack:Error: You must provide a value for the Items parameter.
    at RestClient.<anonymous> (C:\Users\User1\AppData\Roaming\npm\node_modules\process-migrator\node_modules\vso-node-api\node_modules\typed-rest-client\RestClient.js:173:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\User1\AppData\Roaming\npm\node_modules\process-migrator\node_modules\vso-node-api\node_modules\typed-rest-client\RestClient.js:6:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[ERROR] [2018-06-15T07:34:01.645Z] Import failed, see log file for details. Failed to create picklist for field CMMI_D365.Scope, see logs for details.

**Comment by liang2zhu1** [comment]
I'm taking a look but this is somewhat odd - do you mind share the process json (or at minimum the picklist part of it) - feel free obfuscate that as necessary I just want to see the data shape as I did not see the issue on my environment.

**Comment by liang2zhu1** [comment]
@rakeshkasoju Sorry it took a bit long but I finally figured that's because of the pick list does not have any item in it. Also in the VSTS web customization UI this is not rather consistent - you can't create an empty picklist without entries but you are able to remove all entries after creation. I'll give feedback to the team owning that but I imagine this probably won't be a high priority item to be fixed soon.  
If it's important for you to have a picklist without entries, would you mind elaborating a bit more on why?

**Comment by rakeshkasoju** [comment]
Thanks Liang2zhu1

**Comment by Tronko86** [comment]
the problem still occurs
