### ISSUE TITLE
Error: VS402803: Field name '...' you specified is already in use, choose a different name.

### ISSUE THREAD

**Issue by dvdj91** [microsoft/process-migrator#51]
Can there be a skip for fields that were already created in a different process? I keep getting this error because different processes want to use the same custom fields.

**Comment by mpburtt** [comment]
I worked around this problem by giving all my custom fields a prefix (given my time again I might have used a suffix) that should ensure that they're always unique. I think that's likely the only solution as you can't rely on other definitions of the field fitting your requirement (e.g. the existing field might be an integer and you need it to be a string).

Its slightly annoying because, although you can change the label of the field on the work item type to remove the prefix/suffix, when that field is output on a query or you use it on a board card, it always uses the field name and not the label text.

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.
